name: b
version: 0.1.0-nameclaim
description: A Dart library
repository: https://github.com/dkin-om/b.git
issue_tracker: https://github.com/dkin-om/b/issues
homepage: https://github.com/dkin-om/b#readme
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.14.4
